/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thefinancialmodeller;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;



/**
 *Program Name: TheFinancialModeller
 * Module Programming II (COM373)
 * Lecturer: George Wilkie
 * Date:01/12/2015
 * @author Gary McShane - B00656764
 */
public class MyMenu extends javax.swing.JPanel 
{

    /**
     * Creates new form MyMenu
     */
    public MyMenu()
    {
        initComponents();
        //Adding add ActionListeners to the buttons
       btnClose.addActionListener(new CloseListener());
       btnSaveAcc.addActionListener(new SaveListener());
       btnCurrentAcc.addActionListener(new CurrentListener());
        
        
        
    }

    private static class CurrentListener implements ActionListener 
    {         
            @Override
            public void actionPerformed(ActionEvent e)
            {//Ensuring the user enters at least £1.00
                int i = -1;
                String strAmount;
                
                while (i<0)
                {
                   try 
                    {
                        strAmount = JOptionPane.showInputDialog("Enter your initial value");
                        double current = Double.parseDouble(strAmount);
                        
                        if (current >= 1.00 && strAmount.length() > 0)
                        {
                            i++;

                        JFrame CurrentAcc = new JFrame();
                        CurrentAccount currentAccFrame = new CurrentAccount(current);
                        CurrentAcc.setVisible(true);
                        CurrentAcc.setSize(1000,500);
                        CurrentAcc.add(currentAccFrame);
                        }
                        else
                        {
                            JOptionPane.showInputDialog(null,"Please enter your initial value");
                        }
                    }
                   catch(NumberFormatException event)
                   {//Ensuring the a numeric value is inputted
                       JOptionPane.showMessageDialog(null,"You enter a non-numeric value");  
                   }
                            
                }
                
            }
         
    }
    
    class SaveListener implements ActionListener
    {
        @Override
        public void actionPerformed(ActionEvent e)
        {//Ensuring that the user doesn't enter a value under £100
            int i = -1;
            String strAmount;
            
            while(i < 0)
            {           
                strAmount = JOptionPane.showInputDialog("Please enter your initial value:");
                double savings = Double.parseDouble(strAmount);

                if (strAmount.length() > 0 && savings > 100.00)
                {
                    i++;

                    JFrame SavingsAcc = new JFrame();
                    SavingsAccount savingsAccFrame = new SavingsAccount(savings);
                    SavingsAcc.setVisible(true);
                    SavingsAcc.setSize(1000,500);
                    SavingsAcc.add(savingsAccFrame);
                }
                else
                {
                    JOptionPane.showInputDialog(null,"Please enter your initial value");
                }
            }
        }
        
                    
        }
    
    class CloseListener implements ActionListener
    {//This closes the program
      @Override
      public void actionPerformed(ActionEvent e)
      {
        
        System.exit(0);
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblChoice = new javax.swing.JLabel();
        btnCurrentAcc = new javax.swing.JButton();
        btnSaveAcc = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 255));

        lblWelcome.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Welcome to The Financial Modeller System");

        lblChoice.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblChoice.setForeground(new java.awt.Color(204, 204, 204));
        lblChoice.setText("Please select from the following ");

        btnCurrentAcc.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        btnCurrentAcc.setText("Current Account");
        btnCurrentAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurrentAccActionPerformed(evt);
            }
        });

        btnSaveAcc.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        btnSaveAcc.setText("Savings Account ");
        btnSaveAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAccActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(lblWelcome))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblChoice))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnCurrentAcc)
                        .addGap(36, 36, 36)
                        .addComponent(btnSaveAcc)
                        .addGap(44, 44, 44)
                        .addComponent(btnClose)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblWelcome)
                .addGap(39, 39, 39)
                .addComponent(lblChoice)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCurrentAcc)
                    .addComponent(btnSaveAcc)
                    .addComponent(btnClose))
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCurrentAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrentAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCurrentAccActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSaveAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveAccActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCurrentAcc;
    private javax.swing.JButton btnSaveAcc;
    private javax.swing.JLabel lblChoice;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
